### ISSUE TITLE
Unknown column 'expiry_date'

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#250]
REDAXO 5.7beta1, YRewrite 2.4 aus dem Installer beim Ändern des zugewiesenen Templates eines Artikels.

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expiry_date' in 'where clause' in /home//html/pixelfirma/www/redaxo/src/core/lib/sql/sql.php:296 Stack trace: #0 /home//html/pixelfirma/www/redaxo/src/core/lib/sql/sql.php(296): PDOStatement->execute(Array) #1 /home//html/pixelfirma/www/redaxo/src/core/lib/sql/sql.php(341): rex_sql->execute(Array, Array) #2 /home//html/pixelfirma/www/redaxo/src/core/lib/sql/sql.php(840): rex_sql->setQuery('UPDATE `rex_yre...', Array) #3 /home//html/pixelfirma/www/redaxo/src/addons/yrewrite/lib/yrewrite.php(548): rex_sql->update() #4 /home//html/pixelfirma/www/redaxo/src/addons/yrewrite/boot.php(44): rex_yrewrite::generatePathFile(Array) #5 /home//html/pixelfirma/www/redaxo/src/core/lib/extension.php(45): rex_package->{closure}(Object(rex_extension_point)) #6 /home//html/pixelfirma/www/redaxo/src/addons/structure/lib/service_article.php(205): rex_extension::registerPoint(Object(rex_extension_point)) #7 /home//html/pixelfirma/www/redaxo/src/addons/structure/lib/api_functions/api_article_edit.php(26): rex_article_service::editArticle(16, 1, Array) #8 /home//html/pixelfirma/www/redaxo/src/core/lib/api_function.php(178): rex_api_article_edit->execute() #9 /home//html/pixelfirma/www/redaxo/src/core/backend.php(151): rex_api_function::handleCall() #10 /home//html/pixelfirma/www/redaxo/src/core/boot.php(136): require('/home/netsh1013...') #11 /home//html/pixelfirma/www/redaxo/index.php(9): require('/home/netsh1013...') #12 {main} Next rex_sql_exception: Error while executing statement "UPDATE `rex_yrewrite_forward` SET `status` = :status WHERE expiry_date > "0000-00-00" AND expiry_date < :date" using params {"status":0,"date":"2019-01-02"}! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expiry_date' in 'where clause' in /home//html/pixelfirma/www/redaxo/src/core/lib/sql/sql.php:299 Stack trace: #0 /home//html/pixelfirma/www/redaxo/src/core/lib/sql/sql.php(341): rex_sql->execute(Array, Array) #1 /home//html/pixelfirma/www/redaxo/src/core/lib/sql/sql.php(840): rex_sql->setQuery('UPDATE `rex_yre...', Array) #2 /home//html/pixelfirma/www/redaxo/src/addons/yrewrite/lib/yrewrite.php(548): rex_sql->update() #3 /home//html/pixelfirma/www/redaxo/src/addons/yrewrite/boot.php(44): rex_yrewrite::generatePathFile(Array) #4 /home//html/pixelfirma/www/redaxo/src/core/lib/extension.php(45): rex_package->{closure}(Object(rex_extension_point)) #5 /home//html/pixelfirma/www/redaxo/src/addons/structure/lib/service_article.php(205): rex_extension::registerPoint(Object(rex_extension_point)) #6 /home//html/pixelfirma/www/redaxo/src/addons/structure/lib/api_functions/api_article_edit.php(26): rex_article_service::editArticle(16, 1, Array) #7 /home//html/pixelfirma/www/redaxo/src/core/lib/api_function.php(178): rex_api_article_edit->execute() #8 /home//html/pixelfirma/www/redaxo/src/core/backend.php(151): rex_api_function::handleCall() #9 /home//html/pixelfirma/www/redaxo/src/core/boot.php(136): require('/home/netsh1013...') #10 /home//html/pixelfirma/www/redaxo/index.php(9): require('/home/netsh1013...') #11 {main}
```

**Comment by alexplusde** [comment]
Irgendwas war beim Update auf YRewrite 2.4 nicht erfolgreich - reinstall hat es gelöst.
